Parameters:
  ambiente:
    Type: String
    AllowedValues:
     - prod
     - dev
    Default: prod

Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: "vpc-06786ee7f7a163059"
      GroupName: !Sub "SgCloudFormMax-${ambiente}"
      GroupDescription: "Sg montada pelo CloudFormation"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 5001
          ToPort: 5001
          CidrIp: 0.0.0.0/0
  
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-052064a798f08f0d3"
      InstanceType: "t3.nano"
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          SubnetId: "subnet-08ab1cc11d069cf59"
          GroupSet: 
            - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "Ec2-max-cf-${ambiente}"
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum groupinstall "Development Tools" -y
          yum install -y git make
          git clone https://github.com/Max-Leal/proway-docker.git
          cd ./proway-docker
          make requirements
          make run
