version: "3.9"

services:

 backend:
  build: ./backend
  ports:
   - "5001:5000"
  networks:
   - pizzaria-network

 frontend:
  build: ./frontend
  ports:
   - "8080:80"
  volumes:
   - ./frontend/public:/usr/share/nginx/html
  networks:
   - pizzaria-network

networks:
 pizzaria-network:
