on:
  push:
    branches: [ main ]
    
env:
  AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - name: build
        run: |
          ls -la

      - name: checagem
        run: |
          echo "Fazendo a checagem ${{ vars.AWS_ACCESS_KEY }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        id: init
        run: terraform init
    
      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform format
        id: fmt
        run: terraform fmt

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        id: apply
        run: terraform apply -var-file="terraform.tfvars" -auto-approve